# Generated by Django 5.1.3 on 2024-11-23 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_user_sub_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='sub_organization',
        ),
        migrations.DeleteModel(
            name='Sub_Organization',
        ),
    ]
